name: Notifio CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  workflow_dispatch:

env:
  EBAY_CLIENT_ID: ${{secrets.EBAY_CLIENT_ID}}
  EBAY_CLIENT_SECRET: ${{secrets.EBAY_CLIENT_SECRET}}
  EBAY_AUTH_REDIRECT_URL: ${{secrets.EBAY_AUTH_REDIRECT_URL}}
  EBAY_FINDING_API_ENDPOINT: ${{secrets.EBAY_FINDING_API_ENDPOINT}}
  EBAY_SHOPPING_API_ENDPOINT: ${{secrets.EBAY_SHOPPING_API_ENDPOINT}}

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node-18:alphine
    
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run test
        env: 
          DATABASE_URL: postgresql://test:test@localhost:5432/test?schema=public
        run: yarn test:ci
     
